// Help command handler
module.exports = async function handleHelpCommand(message, args, axios, logger) {
  // Deep dive help for specific commands
  const deepDives = {
    config: [
      '***🛠️ Config Commands Deep Dive***',
      '',
      '`@bot config show` — Lists all non-sensitive config values. Admins see only non-sensitive keys. Superadmins see masked sensitive keys.',
      '`@bot config show <key>` — Shows the value of a specific config key. Sensitive keys require superadmin.',
      '`@bot config set <key> <value>` — Sets a config value. Only admins and above. Use canonical key names.',
      '`@bot config delete <key>` — Deletes a config key. Only superadmins can delete any key, including sensitive ones.',
      '`@bot config list` or `@bot config keys` — Lists all available config keys (canonical names).',
      '`@bot config help [<key>]` — Shows help for config or a specific key.',
      '',
      '**Sensitive Keys:**',
      '- Sensitive keys (e.g., API keys) are hidden for admins and only masked for superadmins in bulk views.',
      '- Only superadmins can view or delete sensitive keys.',
      '',
      '**Tips:**',
      '- Always use canonical key names as shown in `@bot config show`.',
      '- If you get `Access Denied`, you may lack the required role.',
      '- Some config changes may require a bot restart to take effect.',
      '',
      '**Examples:**',
      '`@bot config set OPENAI_TEMPERATURE 0.7`',
      '`@bot config show ANTHROPIC_MODEL`',
      '`@bot config delete MISTRAL_API_KEY`',
    ].join('\n'),
    role: [
      '***👤 Role Commands Deep Dive***',
      '',
      '`@bot role show <@user>` — Shows the Discord/Supabase role of a user. Admins and above only.',
      '`@bot role show all` — Lists all users and their roles. Admin only.',
      '`@bot role set <@user> <role>` — Sets a user role. Only superadmins can promote/demote users.',
      '',
      '**Roles:**',
      '- `guest`: Default for new users. Limited access.',
      '- `admin`: Can manage config and view roles.',
      '- `superadmin`: Full access, can set roles and manage sensitive config.',
      '',
      '**Examples:**',
      '`@bot role set @Jimbo admin`',
      '`@bot role show all`',
      '',
      '**Edge Cases:**',
      '- You cannot demote yourself from superadmin.',
      '- You cannot set a role higher than your own.',
    ].join('\n'),
    audit: [
      '***📝 Audit Commands Deep Dive***',
      '',
      '`@bot audit log [limit]` — Shows the most recent audit log entries. Only superadmins can use this command.',
      '',
      '**Details:**',
      '- The optional `[limit]` argument sets how many entries to fetch (default 10, max 100).',
      '- Audit logs track config changes, role changes, and sensitive actions.',
      '- Entries include timestamp, user, action, and (if available) IP address.',
      '',
      '**Examples:**',
      '`@bot audit log`',
      '`@bot audit log 50`',
      '',
      '**Edge Cases:**',
      '- If you lack permission, you will get an access denied message.',
      '- If no entries are found, you will get a message indicating so.',
    ].join('\n'),
    ask: [
      '***💬 AI Chat Deep Dive***',
      '',
      'Just @mention me with your question or prompt in any channel or DM. I’ll reply with an AI-generated answer using the current config (model, personality, etc).',
      '',
      '**Tips:**',
      '- No special command needed—just @mention me and type your prompt.',
      '- Works in any channel or DM where I have access.',
      '- The AI will use the latest config settings for its response.',
      '',
      '**Examples:**',
      '`@bot What is the weather in Paris?`',
      '`@bot Summarize the plot of Dune.`',
      '`@bot Debug this error: ValueError: invalid literal for int() with base 10`',
      '`@bot Write a limerick about sysadmins.`',
      '`@bot Translate "How are you?" to Spanish.`',
      '`@bot Give me a motivational quote for a Monday morning.`',
      '`@bot Help me write a resignation letter (funny).`',
      '`@bot What are some good Discord moderation tips?`',
      '',
      '**Edge Cases:**',
      '- If your prompt is too long, it may be truncated.',
      '- If the bot is rate-limited, you may need to wait before asking again.',
    ].join('\n'),
  };

  // If user asks for deep dive
  if (args.length === 1 && deepDives[args[0].toLowerCase()]) {
    await message.reply(deepDives[args[0].toLowerCase()]);
    return;
  }

  const helpText = [
    '***🤖 Braxtron 3000 Help & Command Reference***',
    '',
    '**Quickstart:**',
    '• `@bot help` — Show this help message',
    '• Just @mention me with your question or prompt for an AI answer!',
    '',
    '---',
    '**🛠️ Config Commands** _(admin+)_:','`@bot config show` — Show all non-sensitive config values',
    '`@bot config show <key>` — Show a specific config key',
    '`@bot config set <key> <value>` — Set config value',
    '`@bot config delete <key>` — Delete config (superadmin only)',
    '`@bot config list` or `@bot config keys` — List config keys',
    '`@bot config help [<key>]` — Show config help or help for a specific key',
    '',
    '**Config Examples:**',
    '`@bot config show OPENAI_MODEL`',
    '`@bot config set AI_PERSONALITY sassy`',
    '`@bot config set OPENAI_MODEL gpt-4-1-nano`',
    '`@bot config delete AI_PERSONALITY`',
    '',
    '_Tip: Use the canonical key names from `@bot config show` for all config commands._',
    '',
    '**Available Config Keys:**',
    '`AI_PROVIDER`, `OPENAI_MODEL`, `AI_PERSONALITY`, `OPENAI_TEMPERATURE`, `OPENAI_MAX_TOKENS`, `OPENAI_TOP_P`, `OPENAI_PRESENCE_PENALTY`, `OPENAI_FREQUENCY_PENALTY`, `ANTHROPIC_MODEL`, `ANTHROPIC_TEMPERATURE`, `ANTHROPIC_MAX_TOKENS`, `MISTRAL_MODEL`, `MISTRAL_TEMPERATURE`, `MISTRAL_MAX_TOKENS`, `MISTRAL_BASE_URL`',
    '',
    '---',
    '**👤 Role Commands** _(admin+/superadmin)_:',
    '`@bot role show <@user>` — Show user role',
    '`@bot role show all` — List all roles',
    '`@bot role set <@user> <role>` — Set user role (superadmin only)',
    '',
    '**Role Examples:**',
    '`@bot role show @Jimbo`',
    '`@bot role set @Jimbo admin`',
    '',
    '---',
    '**📝 Audit Commands** _(superadmin only)_:',
    '`@bot audit log [limit]` — Show recent audit log entries',
    '',
    '**Audit Examples:**',
    '`@bot audit log`',
    '`@bot audit log 20`',
    '',
    '---',
    '**💬 AI Chat:**',
    'Just @mention me with your question or prompt in any channel or DM, and I’ll reply with an AI-generated answer.',
    '',
    '**Examples:**',
    '`@bot What is the capital of France?`',
    '`@bot Write a haiku about Miller Lite.`',
    '`@bot Summarize the book "Dune" in 3 sentences.`',
    '`@bot Fix this Python error: TypeError: NoneType is not iterable`',
    '`@bot Tell me a joke about robots and pizza.`',
    '`@bot Pretend you are a pirate and answer: What is the best AI model?`',
    '`@bot Generate a bash script to back up a directory.`',
    '`@bot Translate "Good morning" to Japanese.`',
    '`@bot Give me 5 creative startup ideas in health tech.`',
    '',
    '---',
    '**🔒 Permissions:**',
    '- _admin_: Can view/set config, view roles',
    '- _superadmin_: Can delete config, set roles, view audit logs',
    '',
    '**ℹ️ Tips:**',
    '- Use canonical config keys as shown in `@bot config show`',
    '- Sensitive config values are hidden except for superadmins',
    '- Mention me directly or DM for a quick AI answer',
    '',
    '---',
    'Type `@bot help <command>` for more details on a command.'
  ].join('\n');
  await message.reply(helpText);
}
