// Help command handler
module.exports = async function handleHelpCommand(message, args, axios, logger) {
  // Deep dive help for specific commands
  const deepDives = {
    config: [
      '***🛠️ Config Commands Deep Dive***',
      '',
      '`@bot config show` — Lists all non-sensitive config values. Admins see only non-sensitive keys. Superadmins see masked sensitive keys.',
      '`@bot config show <key>` — Shows the value of a specific config key. Sensitive keys require superadmin.',
      '`@bot config set <key> <value>` — Sets a config value. Only admins and above. Use canonical key names.',
      '`@bot config delete <key>` — Deletes a config key. Only superadmins can delete any key, including sensitive ones.',
      '`@bot config list` or `@bot config keys` — Lists all available config keys (canonical names).',
      '`@bot config help [<key>]` — Shows help for config or a specific key.',
      '',
      '**Sensitive Keys:**',
      '- Sensitive keys (e.g., API keys) are hidden for admins and only masked for superadmins in bulk views.',
      '- Only superadmins can view or delete sensitive keys.',
      '',
      '**Tips:**',
      '- Always use canonical key names as shown in `@bot config show`.',
      '- If you get `Access Denied`, you may lack the required role.',
      '- Some config changes may require a bot restart to take effect.',
      '',
      '**Examples:**',
      '`@bot config set OPENAI_TEMPERATURE 0.7`',
      '`@bot config show ANTHROPIC_MODEL`',
      '`@bot config delete MISTRAL_API_KEY`',
    ].join('\n'),
    role: [
      '***👤 Role Commands Deep Dive***',
      '',
      '`@bot role show <@user>` — Shows the Discord/Supabase role of a user. Admins and above only.',
      '`@bot role show all` — Lists all users and their roles. Admin only.',
      '`@bot role set <@user> <role>` — Sets a user role. Only superadmins can promote/demote users.',
      '',
      '**Roles:**',
      '- `guest`: Default for new users. Limited access.',
      '- `admin`: Can manage config and view roles.',
      '- `superadmin`: Full access, can set roles and manage sensitive config.',
      '',
      '**Examples:**',
      '`@bot role set @Jimbo admin`',
      '`@bot role show all`',
      '',
      '**Edge Cases:**',
      '- You cannot demote yourself from superadmin.',
      '- You cannot set a role higher than your own.',
    ].join('\n'),
    audit: [
      '***📝 Audit Commands Deep Dive***',
      '',
      '`@bot audit log [limit]` — Shows the most recent audit log entries. Only superadmins can use this command.',
      '',
      '**Details:**',
      '- The optional `[limit]` argument sets how many entries to fetch (default 10, max 100).',
      '- Audit logs track config changes, role changes, and sensitive actions.',
      '- Entries include timestamp, user, action, and (if available) IP address.',
      '',
      '**Examples:**',
      '`@bot audit log`',
      '`@bot audit log 50`',
      '',
      '**Edge Cases:**',
      '- If you lack permission, you will get an access denied message.',
      '- If no entries are found, you will get a message indicating so.',
    ].join('\n'),
    ask: [
      '***💬 AI Chat Deep Dive***',
      '',
      'Just @mention me with your question or prompt in any channel or DM. I’ll reply with an AI-generated answer using the current config (model, personality, etc).',
      '',
      '**Tips:**',
      '- No special command needed—just @mention me and type your prompt.',
      '- Works in any channel or DM where I have access.',
      '- The AI will use the latest config settings for its response.',
      '',
      '**Examples:**',
      '`@bot What is the weather in Paris?`',
      '`@bot Summarize the plot of Dune.`',
      '`@bot Debug this error: ValueError: invalid literal for int() with base 10`',
      '`@bot Write a limerick about sysadmins.`',
      '`@bot Translate "How are you?" to Spanish.`',
      '`@bot Give me a motivational quote for a Monday morning.`',
      '`@bot Help me write a resignation letter (funny).`',
      '`@bot What are some good Discord moderation tips?`',
      '',
      '**Edge Cases:**',
      '- If your prompt is too long, it may be truncated.',
      '- If the bot is rate-limited, you may need to wait before asking again.',
    ].join('\n'),
  };

  // If user asks for deep dive
  if (args.length === 1 && deepDives[args[0].toLowerCase()]) {
    await message.reply(deepDives[args[0].toLowerCase()]);
    return;
  }

  const helpText = [
    '***🤖 Braxtron 3000 Help & Command Reference***',
    '',
    '**Quickstart:**',
    '• `@bot help` — Show this help message',
    '• Just @mention me in any channel or DM with your question or prompt for an AI answer!',
    '',
    '**👤 Role Commands:**',
    '`@bot role show <@user>` — Show a user\'s role',
    '`@bot role show all` — List all users and their roles',
    '`@bot role set <@user> <role>` — Set a user\'s role (superadmin only)',
    '',
    '**📝 Audit Commands:**',
    '`@bot audit log [limit]` — Show audit logs (optionally limited to N entries)',
    '',
    '**🛠️ Config Commands:**',
    '`@bot config show` — Show all non-sensitive config values',
    '`@bot config show <key>` — Show a specific config key',
    '`@bot config set <key> <value>` — Set a config value (admin only)',
    '`@bot config delete <key>` — Delete a config key (superadmin only)',
    '`@bot config list` or `@bot config keys` — List all available config keys',
    '',
    '**💬 AI Chat:**',
    'Just @mention me or DM for a natural language answer using the current model and personality.',
    '',
    '**LLM Command Routing:**',
    '- Natural language requests are routed to commands using an advanced LLM.\n- You can use synonyms for config keys: `model` → `OPENAI_MODEL`, `provider` → `AI_PROVIDER`, `personality` → `AI_PERSONALITY`.',
    '',
    '**Security:**',
    '- Sensitive config keys (API keys, tokens, secrets) are hidden from regular users.\n- Only superadmins can view or delete sensitive keys.',
    '',
    '**Permissions:**',
    '- `admin`: manage config/roles\n- `superadmin`: delete/set roles/audit/config',
    '',
    'Type `@bot help <command>` for deep dives on any command.'
  ].join('\n');
  // Discord message limit is 2000 chars; this is ~900 chars, safe for future expansion.
  await message.reply(helpText);
}
