// Help command handler
module.exports = async function handleHelpCommand(message, args, axios, logger) {
  // You can expand this to fetch help from the gateway or return static help
  const helpText = [
    '**Bot Commands:**',
    '',
    '**Config Commands:**',
    '`@bot config show` — Show current config (admin only)',
    '`@bot config show <key>` — Show a specific config key (admin only)',
    '`@bot config set <key> <value>` — Set config (admin only)',
    '`@bot config delete <key>` — Delete config (superadmin only)',
    '`@bot config list` or `@bot config keys` — List config keys (admin only)',
    '`@bot config help [<key>]` — Show config help or help for a specific key',
    '_Tip: Use the canonical key names shown in `@bot config show` for all config commands._',
    '',
    '**Available Config Keys:**',
    'AI_PROVIDER: Changes the AI backend (openai, anthropic, mistral).',
    'OPENAI_MODEL: Changes the OpenAI model (e.g., gpt-4).',
    'AI_PERSONALITY: Controls the tone/persona of the bot.',
    'OPENAI_TEMPERATURE: Sets the creativity level for OpenAI responses (0.0–1.0).',
    'OPENAI_MAX_TOKENS: Limits max tokens for OpenAI.',
    'OPENAI_TOP_P: Nucleus sampling for OpenAI.',
    'OPENAI_PRESENCE_PENALTY: Penalizes repeated topics (OpenAI).',
    'OPENAI_FREQUENCY_PENALTY: Penalizes frequent word usage (OpenAI).',
    'ANTHROPIC_MODEL: Changes the Anthropic model.',
    'ANTHROPIC_TEMPERATURE: Sets creativity for Anthropic.',
    'ANTHROPIC_MAX_TOKENS: Limits max tokens for Anthropic.',
    'MISTRAL_MODEL: Changes the Mistral model.',
    'MISTRAL_TEMPERATURE: Sets creativity for Mistral.',
    'MISTRAL_MAX_TOKENS: Limits max tokens for Mistral.',
    'MISTRAL_BASE_URL: Base URL for Mistral API (self-hosted).',
    '',
    '**Config Command Examples:**',
    '`@bot config show OPENAI_MODEL`',
    '`@bot config set OPENAI_MODEL gpt-4-1-nano`',
    '`@bot config delete OPENAI_MODEL` (superadmin only)',
    '',
    '**Role Commands:**',
    '`@bot role show <@user>` — Show user role (admin only)',
    '`@bot role show all` — List all roles (admin only)',
    '`@bot role set <@user> <role>` — Set user role (superadmin only)',
    '',
    '**Audit Commands:**',
    '`@bot audit log [limit]` — Show recent audit log entries (superadmin only)',
    '',
    'Just @mention me with your question or prompt and I will reply with an AI-generated answer!'
  ].join('\n');
  await message.reply(helpText);
}
