services:
  # Discord client service
  discord-client:
    build:
      context: ../
      dockerfile: discord-client/Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}      # Discord bot token
      SUPABASE_URL: ${SUPABASE_URL}        # Supabase project URL
      SUPABASE_KEY: ${SUPABASE_KEY}        # Supabase service key
      OPENAI_MODEL: ${OPENAI_MODEL}        # OpenAI model name
      AI_PROVIDER: ${AI_PROVIDER}          # AI provider (e.g., openai)
      AI_PERSONALITY: ${AI_PERSONALITY}    # AI personality config
      LOG_FILE: ${LOG_FILE}                # Log file path
      MCP_SERVER_URL: ${MCP_SERVER_URL}    # MCP memory API endpoint
    depends_on:
      - ai-gateway
      - mcp-memory
    restart: unless-stopped

  # AI gateway service
  ai-gateway:
    build:
      context: ..
      dockerfile: Dockerfile.ai-gateway
    environment:
      PYTHONPATH: /app:/app/mcp_server:/app/common:/app/config_engine
      OPENAI_API_KEY: ${OPENAI_API_KEY}    # OpenAI API key
      SUPABASE_URL: ${SUPABASE_URL}        # Supabase project URL
      SUPABASE_KEY: ${SUPABASE_KEY}        # Supabase service key
      OPENAI_MODEL: ${OPENAI_MODEL}        # OpenAI model name
      AI_PROVIDER: ${AI_PROVIDER}          # AI provider (e.g., openai)
      AI_PERSONALITY: ${AI_PERSONALITY}    # AI personality config
      LOG_FILE: ${LOG_FILE}                # Log file path
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}              # Discord OAuth client ID
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}      # Discord OAuth client secret
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}        # Discord OAuth redirect URI
    # volumes:
    #   - ../config_engine:/app/config_engine
    #   - ../ai_gateway:/app/ai_gateway
    #   - ../mcp_server:/app/mcp_server
    ports:
      - "8000:8000"
    depends_on:
      - mcp-memory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # MCP Memory API service
  mcp-memory:
    build:
      context: ..
      dockerfile: Dockerfile.mcp-memory
    ports:
      - "8001:8001"
    restart: unless-stopped

# Define a default network for inter-service communication
networks:
  default:
    name: ai_discord_bot_network
    driver: bridge