name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_gateway/requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: ruff .
      - name: Run tests
        run: PYTHONPATH=. pytest --maxfail=3 --disable-warnings -q
      - name: Docker build (ai-gateway)
        run: docker build -t ai-gateway-test ./ai_gateway
      - name: Docker build (discord-client)
        run: docker build -t discord-client-test ./discord-client
